const characterModelName: string[] = [
    "BloodDemon1",
    "BloodDemon2",
    "Boomie",
    "DarkOracle1",
    "DarkOracle2",
    "DarkOracle3",
    "ForestGuardian",
    "Halloween",
    "NecromancerGirl1",
    "NecromancerGirl2",
    "OrcShaman1",
    "OrcShaman2",
    "OrcShaman3",
    "Paladin1",
    "Paladin2",
    "Pirate",
    "Samurai",
    "SkeletonDeathKnight1",
    "SkeletonDeathKnight2",
    "SpritiualMonk1",
    "SpritiualMonk2",
    "Guard",
    "Arcanist",
    "Scout",
    "Invoker",
    "Villager"
];

export default characterModelName